- name: Install and Configure nginx
  hosts: web
  become: yes # take sudo privileges to install and manage nginx
  tasks:
    - name: Install nginx
      ansible.builtin.package:  # Use package module to install nginx across all distributions and either RHEL Ubuntu package is baground search for distribution and install nginx 
        name: nginx
        state: present

    - name: Start and enable nginx service
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes

    - name: Create a simple index.html
      ansible.builtin.copy:
        dest: /usr/share/nginx/html/index.html
        content: "<html><body><h1>Welcome to nginx! MDP </h1></body></html>"
 