- name: Variables to print 
  hosts: web 
  vars:  # Define variables at the all play levels use any tasks of this variables
    COURSE: "DEVOPS with AWS"
    DURATION: "3 months"
    TRAINER: "SKR"
  tasks:
    - name: Print course details
      ansible.builtin.debug:
        msg: "Course: {{ COURSE }}, Duration: {{ DURATION }}, Trainer: {{ TRAINER }}"

    - name: Print course details with task level variables
      vars: # Define variables at the task level, this will override the play level variables for this task only
        COURSE: "ANSIBLE with AWS"
        DURATION: "5 months"
        TRAINER: "SKR-bangalore center"
      ansible.builtin.debug:
        msg: "Course: {{ COURSE }}, Duration: {{ DURATION }}, Trainer: {{ TRAINER }}"

    - name: Print course details with task level variables
      ansible.builtin.debug:
        msg: "Course: {{ COURSE }}, Duration: {{ DURATION }}, Trainer: {{ TRAINER }}"