---
- name: Create EC2 and Route53 records
  hosts: localhost
  connection: local
  become: false
  collections:
    - amazon.aws

  vars:
    subnet_id: "subnet-09863c54177764565"
    sg_id: "sg-09a300a3729062c5a"
    ami_id: "ami-09c813fb71547fc4f"
    region: "us-east-1"
    zone: "daws81s.online"
    instances:
    - mysql
    - backend
    - frontend
     

       # keep subnet_id, sg_id, ami_id, zone, etc. here

  tasks:
    - name: Install boto3 and botocore
      ansible.builtin.pip:
        name:
          - boto3
          - botocore
        executable: pip3.9

    - name: Launch EC2 instances
      amazon.aws.ec2_instance:
        name: "{{ item }}"
        vpc_subnet_id: "{{ subnet_id }}"
        instance_type: "t3.micro"
        security_group: "{{ sg_id }}"
        image_id: "{{ ami_id }}"
        key_name: "{{ key_name }}"
        region: "{{ region }}"
      loop: "{{ instances }}"
      register: ec2_instances

    - name: Print EC2 output
      ansible.builtin.debug:
        msg: "{{ ec2_instances }}"

    - name: Create private Route53 records
      amazon.aws.route53:
        state: present
        zone: "{{ zone }}"
        record: "{{ item.item }}.{{ zone }}"
        type: A
        ttl: 60
        value: "{{ item.instances[0].private_ip_address }}"
        wait: true
        overwrite: true
      loop: "{{ ec2_instances.results }}"

    - name: Create public Route53 record for frontend
      amazon.aws.route53:
        state: present
        zone: "{{ zone }}"
        record: "{{ zone }}"
        type: A
        ttl: 60
        value: "{{ item.instances[0].public_ip_address }}"
        wait: true
        overwrite: true
      loop: "{{ ec2_instances.results }}"
      when: item.item == "frontend"

