- name: Terminate EC2 and Route53 records
  hosts: local
  connection: local
  collections:
    - amazon.aws

  vars:
    region: "us-east-1"
    zone: "jioairlines.online"

    instances:
      - mysql
      - backend
      - frontend
      - bastion

  tasks:
    - name: Gather EC2 instances by name
      amazon.aws.ec2_instance_info:
        region: "{{ region }}"
        filters:
          "tag:Name": "{{ item }}"
      loop: "{{ instances }}"
      register: ec2_info

    - name: Terminate EC2 instances
      amazon.aws.ec2_instance:
        region: "{{ region }}"
        instance_ids: "{{ item.instances | map(attribute='instance_id') | list }}"
        state: absent
      loop: "{{ ec2_info.results }}"
      when: item.instances | length > 0

    - name: Delete Route53 records
      amazon.aws.route53:
        state: absent
        zone: "{{ zone }}"
        record: "{{ item }}"
        type: A
      loop:
        - "{{ zone }}"                  # root record
        - "frontend.{{ zone }}"
        - "backend.{{ zone }}"
        - "mysql.{{ zone }}"
        - "bastion.{{ zone }}"
