
172.31.65.106 
172.31.65.108
172.31.65.109
172.31.65.110
172.31.65.111 #ansible_user=ec2-user ansible_ssh_private_key_file=/home/ec2-user/.ssh/ansible.pem
172.31.66.247
172.31.66.248
172.31.66.249 #ansible_user=ec2-user ansible_ssh_private_key_file=/home/ec2-user/.ssh/ansible.pem
172.31.72.70
172.31.72.71
172.31.72.72  #ansible_user=ec2-user ansible_ssh_private_key_file=/home/ec2-user/.ssh/ansible.pem


[local]
localhost # ansible_connection=local 

[mysql]
172.31.65.105 # 13.216.164.132


[backend]
172.31.66.246  # 35.153.28.247


[web]
172.31.72.69 # pip 52.6.198.86




[servers:children]
web
backend
mysql
local


[web:vars]
COURSE="DEVOPS with MULTI-CLOUD FROM INVENTORY"
DURATION="6 months FROM INVENTORY" 
TRAINER="MDP FROM INVENTORY"

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321
; ansible_user=ec2-user
; ansible_ssh_private_key_file=/home/ec2-user/.ssh/ansible.pem


