[local]
localhost ansible_connection=local

[mysql]
mysql.jioairlines.online ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/ansible.pem

[backend]
backend.jioairlines.online ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/ansible.pem

[frontend]
frontend.jioairlines.online ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/ansible.pem






[mysql:vars]
COURSE="DEVOPS with MULTI-CLOUD FROM INVENTORY"
DURATION="6 months FROM INVENTORY"
TRAINER="MDP FROM INVENTORY"
; [local]
; localhost ansible_connection=local

; [mysql]
; mysql.jioairlines.online ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/ansible.pem

; ; [backend]
; ; backend.jioairlines.online ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/ansible.pem

; ; [frontend]
; ; frontend.jioairlines.online ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/ansible.pem

; [servers:children]
; mysql
; backend
; frontend
; local


; [web:vars]
; COURSE="DEVOPS with MULTI-CLOUD FROM INVENTORY"
; DURATION="6 months FROM INVENTORY" 
; TRAINER="MDP FROM INVENTORY"
