
172.31.65.106 

[local]
localhost # ansible_connection=local 


[mysql]
mysql.jioairlines.online

[backend]
backend.jioairlines.online  # 35.153.28.247

[frontend]
frontend.jioairlines.online # pip 52.6.198.86




[servers:children]
web
backend
mysql
local

[all:vars]
ansible_user=ec2-user
ansible_ssh_private_key_file=~/Downloads/ansible.pem




[web:vars]
COURSE="DEVOPS with MULTI-CLOUD FROM INVENTORY"
DURATION="6 months FROM INVENTORY" 
TRAINER="MDP FROM INVENTORY"

#[all:vars]
#ansible_user=ec2-user 
#ansible_password=DevOps321 
#ansible_ssh_common_args='-o PreferredAuthentications=password'
; [all:vars]
; ansible_user=ubuntu
; ansible_ssh_private_key_file=~/Downloads/ansible.pem
; ansible_ssh_common_args='-o StrictHostKeyChecking=no'


; [mysql]
; 172.31.2.247 
; ansible_user=ubuntu 
; ansible_ssh_private_key_file=~/.ssh/ansible.pem


; #ansible_ssh_private_key_file=~/ansible.pem
; ansible_ssh_common_args='-o StrictHostKeyChecking=no'

; [mysql]
; 172.31.2.247 ansible_user=ubuntu ansible_ssh_private_key_file=/path/to/your-key.pem

; [defaults]
; private_key_file = /home/ubuntu/Downloads/ansible.pem
; remote_user = ubuntu

; ansible_ssh_private_key_file=/home/ubuntu/Downloads/ansible.pem


